# Generated by Django 3.1.7 on 2022-12-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('phone_number', models.CharField(max_length=20)),
                ('open_hours', models.CharField(max_length=200)),
                ('website', models.URLField()),
            ],
        ),
    ]
