# Generated by Django 3.1.7 on 2022-12-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_offer',
            field=models.BooleanField(default=False),
        ),
    ]
