# Generated by Django 3.1.7 on 2022-12-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supermarkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.URLField()),
                ('address', models.CharField(max_length=255)),
                ('open_state', models.CharField(default='', max_length=255)),
                ('operating_hours', models.CharField(max_length=200)),
                ('website', models.URLField(max_length=255)),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
